name: 01-main Tests

on:
  pull_request:
    types: [opened, closed, synchronize]
    paths:
      - "01-main/packages/*"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update

          # Dependencies to build the deb
          # sudo apt-get install build-essential devscripts debhelper -y

          # Dependencies for deb-get itself
          sudo apt-get install apt apt-transport-https bash coreutils curl dpkg gpg grep libc-bin lsb-release sed software-properties-common sudo wget -y

          # Build
          echo "here" && sudo bash ./01-main/packages/deb-build.sh

