on:
  push:

name: Create-Release

jobs:
  build: 
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        run: sudo apt-get install build-essential devscripts debhelper apt apt-transport-https bash coreutils curl dpkg gpg grep libc-bin lsb-release sed software-properties-common sudo wget -y
      - name: Checkout code
        uses: actions/checkout@main
      - name: Doing the build
        run: sudo bash deb-build.sh

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.run_number }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ../deb-get_0.3.6-1_all.deb
          asset_name: deb-get_0.3.6-1_all.deb
          asset_content_type: application/binary
