on: [push]

name: Create-Release

jobs:
  build: 
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        run: sudo apt-get install curl #build-essential devscripts debhelper apt apt-transport-https bash coreutils dpkg gpg grep libc-bin lsb-release sed software-properties-common sudo wget -y
      - name: Checkout code
        uses: actions/checkout@v3
      #- name: Doing the build
      #  run: sudo bash deb-build.sh
      - name: simulate build
        run: echo "simulate" && touch ../deb-get_0.3.6-1_all.deb
      - name: list files2
        run: ls -la ..

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - Change 1
            - change 2
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: ../deb-get_0.3.6-1_all.deb
